[package]
name = "hello_gpu"
version = "0.1.0"
authors = ["Maxime <emixampons@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = "*"